### ISSUE TITLE
Topic: HATEOAS on datasets

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres-front#52]
The current topics API implementation won't scale to hundreds or even thousands of datasets, as is forecasted for the main ecospheres topic.

- all datasets are deserialized in the topics' GET endpoints (details, list)
- when adding a dataset to a topic, we need to pass all the existing datasets in the array

Proposed solution is similar to what has been done in API v2 for `datasets/{id}/resources`. We could get a reference to the list of datasets in the root GET endpoints for topics and then query a paginated list of datasets for each topic. Similarly, we could POST to `/topics/{id}/datasets/` to add datasets without passing all the existing datasets.

**Comment by maudetes** [comment]
Alternative workaround to scale : using `X-fields` header to mask needed fields only: https://flask-restplus.readthedocs.io/en/0.8.1/mask.html

**Comment by abulte** [comment]
Agreed, and then use the search endpoint to get a paginated list of datasets by topic.

**Comment by abulte** [comment]
NB: workaround is only for read, not write.

**Comment by streino** [comment]
Write (append) is a "should have" leaning toward "must have" for the "Ecosphères" topic/universe.
We're talking about thousands of datasets.

**Comment by maudetes** [comment]
Concerning scaling at write time, if you want to update the existing list of datasets, you'll need the list of datasets ids only, not their details.
```
"datasets": ["545b55e1c751df52de9b6045", "651fb828ee43f268b24e8502", "53699fe4a3a729239d206227"],
```
For 5000 datasets, it takes ~10 seconds. I guess it depends how often you want to update the list, and how many thousands you target, to know if it's a must have or not.

In my opinion, the issue is also about having a cleaner REST pattern at write time. I wonder if we could break the API in an upcoming major udata version instead of adding an API v2, since topics [have been deprecated since March 2022](https://github.com/opendatateam/udata/blob/master/CHANGELOG.md#332-2022-03-01).

**Comment by abulte** [comment]
@maudetes I don't think anyone apart from us is using the topics API, seems breakable. But might be cleaner on your side if proper/refactored endpoints are all moved to v2? You might even remove the topics v1 API. Up to you :-)

**Comment by streino** [comment]
I get the following error after 45s trying to push 85K datasets (from all orgs [listed here](https://github.com/ecolabdata/ecospheres-front/blob/main/config.yaml#L23)):
```
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://demo.data.gouv.fr/api/1/topics/ecospheres-feed-test/
```
Pushing only the list of ids (and tags because otherwise it fails 🤨).

As a side note, it takes a (dumb sequential) script about 7 mn to build the list of IDs hitting the orgs API with `X-Fields=data{id},next_page`. Not a major blocker but a waste of time when we only want to add a few datasets or a new org.
